[package]
name = "gfeats"
version = "0.1.0"
edition = "2021"
authors = ["Chris cyogodzi@gmail.com"]

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }

[lib]
name = "genefeatures"
path = "src/genefeatures/lib.rs"

