[package]
name = "gfeats"
version = "0.1.0"
edition = "2021"
authors = ["Chris cyogodzi@gmail.com"]

[dependencies]
bio-seq = "0.13.0"
lazy_static = "1.5.0"
regex = "1.10.5"
clap = { version = "4.5.9", features = ["derive"] }

[lib]
name = "genefeatures"
path = "src/genefeatures/lib.rs"