name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create --file environment.yml --name gf
        sudo apt-get install libcurl4-openssl-dev
        wget https://github.com/samtools/samtools/releases/download/1.20/samtools-1.20.tar.bz2
        tar -vxjf samtools-1.20.tar.bz2
        cd samtools-1.20
        make
        cd ..
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda init
        conda activate gf
        sampath=$(pwd)/samtools-1.20
        export PATH="$PATH:${sampath}"
        conda install pytest
        pytest
